### PR TITLE
Make poll automatically open a thread

### PR DESCRIPTION
**Pull request by elkowar**
This PR makes !poll auto-open a thread to discuss the poll.

### CODE REVIEW

**Comment by 6gk** [comment]
it should only do this in #polls, doesn't make sense to make a new thread mid-convo in lounge or something

**Comment by elkowar** [comment]
if you look at it, very rarely is !poll used outside of the mod-internal poll channel, and imo in many of the cases where it is used outside, it would make sense

**Comment by 6gk** [comment]
eh.  #polls is﻿ not in﻿t﻿e﻿n﻿d﻿ed fo﻿r﻿ d﻿i﻿s﻿cu﻿ss﻿ion, whereas most other places are.  cluttering #polls with discussion, is an issue, "cluttering" #lounge with discussion is not.

also, i would imagine most polls are contextual. and you know how hard it is to move an ongoing discussion.

**Comment by elkowar** [comment]
@mlvzk this PR now requires a new env var to be set: `CHANNEL_MOD_POLLS` to the polls channel id

**Comment by 6gk** [comment]
thx bby ily uwu

**Pull request merged**
