### PR TITLE
Clickable bot channel

### PR DESCRIPTION
**Pull request by L3afMe**

### CODE REVIEW

**Comment by elkowar** [comment]
Not a fan of hardcoding the bot-channel id/link here. Instead, We should probably add a `channel_bot` to `Config` and reference that.

**Comment by 6gk** [comment]
Now that we can hl in dms, why not just remove the "in #bot" bit? @willeccles seems like a job for the epic fixer of bad languages

**Comment by willeccles** [comment]
I have literally no idea what any of this means, but I'll get to it in 5-10 business weeks 👍

**Comment by 6gk** [comment]
@willeccles i think it's been a bit more than that?

**Pull request closed without merging**
