### PR TITLE
add user matching via `user#1234`

### LINKED ISSUE #182: [BUG] user matching with `user#1234` doesn't work
## Expected behaviour
Works

## Current behaviour
Doesn't work :/

ie `!fetch gk#7186` should look for the user "gk" with the number "7186", and not a user with the (nick|user)name "gk#7186"

### PR DESCRIPTION
**Pull request by LtPeriwinkle**
fixes #182

### CODE REVIEW

**Comment by elkowar** [comment]
having to loop through all members of the guild on every command that mentions a user would be,... _very_ inefficient :/

**Comment by 6gk** [comment]
possibly

**Comment by elkowar** [comment]
A bit, as that queries the discord API. however, I'm not sure how that would impact our rate-limiting - it _should_ be fine tho, given that there's comparatively few command invocations generally

**Comment by mlvzk** [comment]
> having to loop through all members of the guild on every command that mentions a user would be,... _very_ inefficient :/

That's how it worked in Trup and it wasn't a bottleneck.

The .tag() function does allocation, it's better to use user.name and user.discriminator.

**Comment by elkowar** [comment]
@mlvzk given that discord has speicifc api for this, I'd argue using that probably still makes more sense, no? assuming that it works as expected

**Comment by 6gk** [comment]
@elkowar @mlvzk :+1: i approve of this feature.

**Comment by LtPeriwinkle** [comment]
hey, sorry for the incredibly long turnaround time on this. `search_members` will get anything where the username starts with the provided string, so I'm thinking it only makes sense to check the discriminator if there's more than one user that matches, right? otherwise, it must be the person you're looking for, so there's no point, i think.

**Comment by 6gk** [comment]
> so I'm thinking it only makes sense to check the discriminator if there's more than one user that matches, right?

I disagree -- a couple issues:

 - discord fucks up and doesn't give all the applicable results, leading to a wrongping:tm:
 - user left the server, and another user by the same name is still in it, leading to a wrongping:tm:

**Comment by 6gk** [comment]
why did i add that tag lol

**Comment by LtPeriwinkle** [comment]
Looks like clippy is complaining because of an issue somewhere that I didn't change, should I fix that in this pr too so that it doesn't fail?

**Comment by AusCyberman** [comment]
> Looks like clippy is complaining because of an issue in highlights.rs, should I fix that in this pr too so that it doesn't fail?

yes.

**Comment by druskus20** [comment]
@LtPeriwinkle So I tested it and cleaned up the code a bit, mainly:

```rs
if members.len() == 1 {
    if members[0].user.discriminator == discriminator {
        Ok(Some(members[0].user.id))
    } else {
        Ok(None)
    }
} else {
    let user = members
        .iter()
        .find(|m| m.user.name == name && m.user.discriminator == discriminator)
        .map(|m| m.user.id);
    Ok(user)
}
```
The first part of this `if` isn't necessary, as we can default to `members.iter()`
```rs
Ok(members
    .iter()
    .find(|m| {
        m.user.name.to_lowercase() == name.to_lowercase()
            && m.user.discriminator == discriminator
    })
    .map(|m| m.user.id))
```
Also:
```rs
m.user.name == name && m.user.discriminator == discriminator
```
The comparison in `.find` doesn't work, because `m.user.name` contains uppercase. So I added `to_lowercase` to both sides of the operation.
```rs
m.user.name.to_lowercase() == name.to_lowercase()
```

**Review by druskus20 — APPROVED** [review]

**Pull request merged**
